/**
 * Build a BibTeX entry for one included paper. Tries to use the
 * paper's externalDoi or externalArxivId when present; falls back to
 * a generic `@misc` shape with whatever URL / source info exists.
 *
 * The citation key matches the draft's `[paper_id]` style so a
 * researcher can search-and-replace the key into LaTeX manuscripts
 * directly. Keys are sanitised to BibTeX's allowed character set
 * (alphanumeric + `-_:`).
 */
export type BibTexPaper = {
  /** Stable id used in the draft as `[paper_XXX]`. */
  citationKey: string;
  /** Falls back to "Untitled paper" when missing — BibTeX requires SOMETHING. */
  title: string | null;
  /** Cross-reference; one or both may be null. */
  externalDoi: string | null;
  externalArxivId: string | null;
  /** R2 blob key for uploaded items, e.g. "corpus/<projectId>/<uuid>.pdf". */
  source: string | null;
  /**
   * Bibliographic metadata (M97). Populated for V2 discovered papers
   * from the DiscoveredPaper row; null for uploaded PDFs where only the
   * OCR'd title is known. A BibTeX entry without author + year is barely
   * usable in a real manuscript, so we emit these when available.
   */
  authors?: string[] | null;
  year?: number | null;
  venue?: string | null;
};

/**
 * Escape BibTeX special characters inside a `{...}`-wrapped value.
 *
 * Always-escape: `\` `{` `}` `@` `%` `$` `&` `#`.
 *   - `\` `{` `}` would break the wrapper or be reinterpreted.
 *   - `@` introduces a new entry in some parsers.
 *   - `%` is BibTeX's line-comment marker — UNESCAPED, "Cost 50% off"
 *     would comment out the closing `}` and corrupt the whole entry.
 *   - `$` enters LaTeX math mode at render time. Escaping with `\$`
 *     is the universally-honoured literal.
 *   - `&` `#` are reserved LaTeX columns/parameters; `\&` `\#` is the
 *     universal literal form.
 *
 * Not escaped: `_` `^` `~` — these are LaTeX specials too, but the
 * canonical fix in BibTeX practice is to wrap the whole value (which
 * we do) or use a dedicated LaTeX-Unicode renderer downstream. The
 * surface we ship is BibTeX-correctness, not pretty-LaTeX-rendering.
 */
function bibtexEscape(value: string): string {
  return value.replace(/[\\{}@%$&#]/g, (m) => `\\${m}`);
}

function sanitiseKey(key: string): string {
  // BibTeX citation keys allow alphanumeric + `-_:.` in most engines
  // (biber + biblatex + bibtex). Replace anything outside that set
  // (e.g. forward slashes in DOIs) with `_` so a key like `10.1/foo`
  // becomes `10.1_foo`. Dots stay so DOI-shaped keys remain
  // recognisable.
  return key.replace(/[^A-Za-z0-9\-_:.]/g, "_") || "untitled";
}

export function paperToBibtex(p: BibTexPaper): string {
  const key = sanitiseKey(p.citationKey);
  const title = bibtexEscape(p.title ?? "Untitled paper");

  // Prefer @article when there's a DOI (a published paper). Otherwise
  // @misc which is the BibTeX catch-all for arXiv preprints + grey
  // literature.
  const entryType = p.externalDoi ? "article" : "misc";

  const fields: string[] = [`  title = {${title}}`];
  // Author list: BibTeX joins multiple authors with " and ". Each
  // author is emitted verbatim (escaped) — we don't try to reformat
  // "First Last" → "Last, First" since the provider data is already in
  // display order + reformatting risks mangling non-Western name order.
  if (p.authors && p.authors.length > 0) {
    const authorField = p.authors.map((a) => bibtexEscape(a)).join(" and ");
    fields.push(`  author = {${authorField}}`);
  }
  if (p.year != null) {
    fields.push(`  year = {${p.year}}`);
  }
  if (p.venue) {
    // `journal` is the @article-canonical field; @misc tolerates it +
    // most engines surface it as the publication venue regardless.
    fields.push(`  journal = {${bibtexEscape(p.venue)}}`);
  }
  if (p.externalDoi) {
    fields.push(`  doi = {${bibtexEscape(p.externalDoi)}}`);
    fields.push(`  url = {https://doi.org/${bibtexEscape(p.externalDoi)}}`);
  }
  if (p.externalArxivId) {
    fields.push(`  eprint = {${bibtexEscape(p.externalArxivId)}}`);
    fields.push(`  archivePrefix = {arXiv}`);
    if (!p.externalDoi) {
      fields.push(`  url = {https://arxiv.org/abs/${bibtexEscape(p.externalArxivId)}}`);
    }
  }
  if (!p.externalDoi && !p.externalArxivId && p.source) {
    // Uploaded PDFs with no DOI/arxiv id — capture the source path so
    // the citation isn't dangling.
    fields.push(`  note = {Uploaded PDF: ${bibtexEscape(p.source)}}`);
  }

  return `@${entryType}{${key},\n${fields.join(",\n")},\n}`;
}

export function buildBibtexFile(papers: BibTexPaper[]): string {
  if (papers.length === 0) {
    return "% No papers included in this review.\n";
  }
  const header = "% Generated by Thoth (https://thoth-slr.vercel.app).\n";
  return header + papers.map(paperToBibtex).join("\n\n") + "\n";
}
