import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";

/**
 * Download a completed Run's draft as a Markdown file.
 *
 * Returns 404 for "no such run", "not yours", or "no draft yet" — same
 * existence-probe defense as the rest of the API.
 *
 * Filename in Content-Disposition includes the run id + ".md" so a user
 * can download multiple drafts without naming collisions in their
 * Downloads folder.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await requireUser().catch(() => null);
  if (!user) return new NextResponse("Unauthorized", { status: 401 });

  const { id } = await params;
  const run = await db.run.findUnique({
    where: { id },
    select: {
      draft: true,
      project: { select: { ownerId: true } },
    },
  });
  if (!run || run.project.ownerId !== user.id || !run.draft) {
    return new NextResponse("Not found", { status: 404 });
  }

  return new NextResponse(run.draft, {
    status: 200,
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      // Filename is "thoth-<runId>.md" — collision-proof + lets users
      // grep for "thoth-" in their Downloads folder.
      "content-disposition": `attachment; filename="thoth-${id}.md"`,
      // Don't cache — the draft can be regenerated by a follow-up run,
      // and stale downloads would be misleading.
      "cache-control": "no-store",
    },
  });
}
