import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { buildRunFilename } from "@/lib/download-filename";

/**
 * Download a completed Run's draft as a Markdown file.
 *
 * Returns 404 for "no such run", "not yours", or "no draft yet" — same
 * existence-probe defense as the rest of the API.
 *
 * Filename includes a slug of the project title + the run's date
 * (YYYY-MM-DD) so multiple downloads sort sensibly in Downloads:
 * `thoth-archaeal-hibernation-2026-05-28.md`.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const user = await requireUser().catch(() => null);
  if (!user) return new NextResponse("Unauthorized", { status: 401 });

  const { id } = await params;
  const run = await db.run.findUnique({
    where: { id },
    select: {
      draft: true,
      createdAt: true,
      completedAt: true,
      question: true,
      project: { select: { ownerId: true, title: true } },
    },
  });
  if (!run || run.project.ownerId !== user.id || !run.draft) {
    return new NextResponse("Not found", { status: 404 });
  }

  const filename = buildRunFilename({
    projectTitle: run.project.title,
    runId: id,
    startedAt: run.createdAt,
    suffix: "md",
  });

  // Prepend an HTML-comment provenance header so a researcher who archives
  // the .md can identify the source review later. HTML comments render to
  // nothing in every common Markdown processor (Pandoc, GFM, react-markdown,
  // mkdocs) so the prepended block is invisible when the draft is rendered
  // but preserved as text in the file. Sanitise embedded `--` to avoid
  // accidentally closing the comment.
  const sanitise = (s: string) => s.replace(/--/g, "- -");
  const header = [
    "<!--",
    `  Thoth review draft`,
    `  Project: ${sanitise(run.project.title)}`,
    `  Question: ${sanitise(run.question)}`,
    `  Run started: ${run.createdAt.toISOString()}`,
    run.completedAt ? `  Run completed: ${run.completedAt.toISOString()}` : null,
    `  Generated: ${new Date().toISOString()}`,
    "-->",
    "",
  ].filter(Boolean).join("\n");

  return new NextResponse(header + run.draft, {
    status: 200,
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
      // Don't cache — the draft can be regenerated by a follow-up run,
      // and stale downloads would be misleading.
      "cache-control": "no-store",
    },
  });
}
